{% set name = "modelcif" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modelcif-{{ version }}.tar.gz
  sha256: e7055c5da9b9da0c7d2358c792b61a147e1f7d5756ecbdafccfd15cd9f3b66e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ihm >=0.34
    - python >=3.6

test:
  imports:
    - modelcif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ihmwg/python-modelcif
  summary: Package for handling ModelCIF mmCIF and BinaryCIF files
  license: MIT
  license_file: LICENSE
  description: |
    This is a Python package to assist in handling mmCIF
    (http://mmcif.wwpdb.org/) and BinaryCIF
    (https://github.com/dsehnal/BinaryCIF) files compliant with the
    ModelCIF extension
    (https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Index/).
    It works with Python 2.7 or Python 3.

    Please see the documentation at https://python-modelcif.readthedocs.org/
    or some worked examples at
    https://github.com/ihmwg/python-modelcif/tree/main/examples
    for more details.
  doc_url: https://python-modelcif.readthedocs.io/
  dev_url: https://github.com/ihmwg/python-modelcif

extra:
  recipe-maintainers:
    - benmwebb
