{% set name = "modelcif" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modelcif-{{ version }}.tar.gz
  sha256: 67f45ddcb9fa111be984d385167ad5cc182fc9ad5a194c523a7438dd3a140012

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ihm >=0.34
    - python >=3.6

test:
  imports:
    - modelcif
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ihmwg/python-modelcif
  summary: Package for handling ModelCIF mmCIF and BinaryCIF files
  license: MIT
  license_file: LICENSE
  description: |
    This is a Python package to assist in handling mmCIF
    (http://mmcif.wwpdb.org/) and BinaryCIF
    (https://github.com/dsehnal/BinaryCIF) files compliant with the
    ModelCIF extension
    (https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Index/).
    It works with Python 2.7 or Python 3.

    Please see the documentation at https://python-modelcif.readthedocs.org/
    or some worked examples at
    https://github.com/ihmwg/python-modelcif/tree/main/examples
    for more details.
  doc_url: https://python-modelcif.readthedocs.io/
  dev_url: https://github.com/ihmwg/python-modelcif

extra:
  recipe-maintainers:
    - benmwebb
