{% set name = "modelcif" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/modelcif-{{ version }}.tar.gz
  sha256: 517d2a7be67c96fd56dcc3b50cf7bb0b130958c325653d9925f9a5dbfe151d78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ihm >=1.7
    - python >={{ python_min }}

test:
  imports:
    - modelcif
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ihmwg/python-modelcif
  summary: Package for handling ModelCIF mmCIF and BinaryCIF files
  license: MIT
  license_file: LICENSE
  description: |
    This is a Python package to assist in handling mmCIF
    (http://mmcif.wwpdb.org/) and BinaryCIF
    (https://github.com/dsehnal/BinaryCIF) files compliant with the
    ModelCIF extension
    (https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Index/).
    It works with Python 2.7 or Python 3.

    Please see the documentation at https://python-modelcif.readthedocs.org/
    or some worked examples at
    https://github.com/ihmwg/python-modelcif/tree/main/examples
    for more details.
  doc_url: https://python-modelcif.readthedocs.io/
  dev_url: https://github.com/ihmwg/python-modelcif

extra:
  recipe-maintainers:
    - benmwebb
